### ISSUE TITLE
As a person who struggles with technology/is inexperienced with technology, I can still easily navigate Dukepital’s interface 

### ISSUE THREAD

**Issue by qjie7** [AY1920S1-CS2113-T13-2/main#11]

**Comment by qjie7** [comment]
so that i would not trouble someone else, saving me a lot of frustration and time , as well as others.

**Comment by lmtaek** [comment]
Navigation via the GUI is generally manageable at this point--too many PRs to reference, in this case. 

Navigability of the GUI via the CLI is likely a step worth considering, but that will be implemented into a different issue.
