### ISSUE TITLE
Implement typo auto-correction for command input using LevensteinDistance algo

### ISSUE THREAD

**Issue by HUANGXUANKUN** [AY1920S1-CS2113-T13-2/main#111]
It is to resolve issue: #21 _As a nurse in a rush, I can still type things with typos and get the outcome from Duke that I want_

General idea: Implement an algorithm to perform string approximation

Details: 

- **By matching a string to a nearest String from a pre-defined dictionary containing command keywords by calculating the Levenstein Distance.**

- **Proximity of the English Keyboard is not accounted for now.**

- Example: 

  - input command: `list patiemts`, the typo `patiemts` will match with pre-defined word `patients`

Potential APIs:

1. org.apache.lucene.search.spell 

     - NGramDistance, LevensteinDistance, JaroWinklerDistance

2. google spell check (this api only works online, looking for an offline replacement)

3. http://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#getLevenshteinDistance%28java.lang.CharSequence,%20java.lang.CharSequence%29

**Comment by lmtaek** [comment]
Addressed in PR #127 . The feature is usable via the CLI, though it is still experiencing some difficulties within the GUI. These issues have been documented in the Issue tracker. Thus, this specific issue (involving the feature's implementation) is resolved.
