### ISSUE TITLE
`delete patient task` bug involving lack of output

### ISSUE THREAD

**Issue by lmtaek** [AY1920S1-CS2113-T13-2/main#150]
Steps taken:
1. Started up Duke
2. Typed in `delete patient task #3 5`

Received:
<img width="434" alt="Screen Shot 2019-10-22 at 1 51 12 PM" src="https://user-images.githubusercontent.com/43768091/67261596-fbb91b80-f4d3-11e9-9598-a2fb51f387c0.png">

**Comment by WEIFENG-NUSCEG** [comment]
hmmm I think this is caused by the wrong format of input and our miscommunication.
