### ISSUE TITLE
[Bug] Invalid data format is saved even Exception has been thrown

### ISSUE THREAD

**Issue by HUANGXUANKUN** [AY1920S1-CS2113-T13-2/main#154]
**Summary**:  @WEIFENG-NUSCEG In AssignPatientToTaskCommand,  command with invalid data format executed successfully. The invalid data format is being saved to local file, causing data corruption. 

**Replication**: Enter invalid AssignCommand `assign standardtask #3 1 27/12/2020 164invalid`

**Expected Output**: Exception is thrown to warn user the invalid date format

**Actual Output**: After Exception is being thrown, the command continues to execute and invalid data is being saved.

![image](https://user-images.githubusercontent.com/39436447/67286119-69346e80-f50b-11e9-8f5b-a4526ef40d6b.png)

**Comment by WEIFENG-NUSCEG** [comment]
This bug has been solved in this PR #149
