### ISSUE TITLE
[BUG] Correct command leads to activation of typo corrector

### ISSUE THREAD

**Issue by qjie7** [AY1920S1-CS2113-T13-2/main#165]
Summary:
@HUANGXUANKUN  This bug is shown when i trying to add patient.

Bug replicate:
Step 1: Enter a correct add command eg. add patient:qian jie:s123:A09:NIL
<img width="289" alt="Screenshot 2019-10-23 at 8 18 02 PM" src="https://user-images.githubusercontent.com/47095237/67391927-37d2a600-f5d2-11e9-8240-df6c77207f97.png">

Expected output : There should not be Ambiguous format error check here

Current output : 
<img width="304" alt="Screenshot 2019-10-23 at 8 17 16 PM" src="https://user-images.githubusercontent.com/47095237/67391882-1d003180-f5d2-11e9-9822-244c735ebc77.png">

The same problem appear in other command class as listed below:
<img width="301" alt="Screenshot 2019-10-23 at 8 24 47 PM" src="https://user-images.githubusercontent.com/47095237/67392530-48cfe700-f5d3-11e9-8a95-91581165f5e8.png">

**Comment by lmtaek** [comment]
Resolved with #287 .
