### ISSUE TITLE
Continually update + enhance GUI's handling of Dukepital features...

### ISSUE THREAD

**Issue by lmtaek** [AY1920S1-CS2113-T13-2/main#201]
...so that functionality within the GUI matches the functionality within the CLI, but in a more user-friendly manner.

**Comment by HUANGXUANKUN** [comment]
Thanks @lmtaek . Will be doing this on Friday night

**Comment by lmtaek** [comment]
Seems like #286 serves as the last PR for this issue specifically. From here on out, bug fixing + documentation + dynamic data production should be our concerns.
