### ISSUE TITLE
As a nurse, I can remove tasks from a list 

### ISSUE THREAD

**Issue by qjie7** [AY1920S1-CS2113-T13-2/main#6]

**Comment by qjie7** [comment]
so that I can keep my plans more organized, and will remember not to do unnecessary tasks.

**Comment by lmtaek** [comment]
Relevant to PR #149 . Will continuously be updating features for more flexibility--will create Issues detailing more specific fixes for this, rather than updating this issue repeatedly.

**Comment by kkeejjuunn** [comment]
Solved by #101
