### ISSUE TITLE
As a nurse, I can remove a task assigned to a patient when they no longer need it...

### ISSUE THREAD

**Issue by qjie7** [AY1920S1-CS2113-T13-2/main#8]
...so that I do not do unnecessary tasks.

**Comment by qjie7** [comment]
so that they’re easy to create (not time-consuming), and easy to look at later.

**Comment by lmtaek** [comment]
Relevant to PR #149 . Will continuously be updating features for more flexibility--will create Issues detailing more specific fixes for this, rather than updating this issue repeatedly.
