### ISSUE TITLE
Implement Parser method for 'assign'

### ISSUE THREAD

**Issue by lmtaek** [AY1920S1-CS2113-T13-2/main#98]
Expected to parse a singular command line: specifically by ID. 

EX: `assign by id: <task type> <patient ID> <task ID> <deadline>` OR `assign by id: <task type> <patient ID> <task ID> <start time> <end time>`.

Related to Epic #95 .

**Comment by WEIFENG-NUSCEG** [comment]
issues has been solved by #90

**Comment by lmtaek** [comment]
This issue doesn't involve the ability of the system to actually assign the task--it's more about taking the input and translating it into something that the executing command can use. @WEIFENG-NUSCEG 

With PR #110 we should be able to use `assign by id: ` to get the same outcome as originally desired. The command formats look like this, now:

Standard task: `assign by id: S <PATIENT_ID> <TASK_ID> <TIME>
Event task: `assign by id: E <PATIENT_ID> <TASK_ID> <START_TIME> to <END_TIME>`

**Comment by lmtaek** [comment]
Resolved with #110
